### ISSUE TITLE
Create State and Activity diagrams

### ISSUE THREAD

**Issue by invalid04** [CalebTB/Group15-IntrotoSE#13]

**Comment by Preston-Leeroy** [comment]
![User 1 3 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520151-a64a1e49-4477-4f48-b8a7-21709a9bf56b.png)
![User 1 2 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520172-847814f3-cc8d-417e-96fb-3ea52966f8f3.png)
![User 1 1 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520237-195c7574-6f1c-45da-8055-23b443f03b11.png)

**Comment by Preston-Leeroy** [comment]
![User 1 1 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520795-50a22993-89a6-4f7c-bf48-d96cf603426d.png)
![User 1 2 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520803-3031f4ab-ac0b-4856-b841-4dbbd13f10db.png)
![User 1 3 Behavorial Model](https://user-images.githubusercontent.com/124001889/226520805-f45abea5-f0e2-48f0-85fd-e9bb0432825e.png)
